/*! Open Historia — preset fleet rebuild © 2026 Nicholas Krol, MIT (see src/Editor/LICENSE). */
// Regenerate EVERY preset scenario from its spec, then re-sync prompt packs —
// one command, so "the presets" can never be half-current again:
//
//   node scripts/presets/rebuild-all.mjs
//
// Order matters twice: prompts.json is copied from the default scenario at
// build time and then sync-prompts refreshes the changed keys from the current
// JS defaults, so a rebuild always ends on the newest prompt text. And the
// manifest merge is idempotent, so rerunning this is always safe. Requires
// public/assets/regions.pmtiles and cities-seed.json (repo install assets).
//
// The generated folders are LARGE (each regions.geojson clones the world seed)
// and deliberately gitignored — the SPECS are the source of truth; scenario
// folders are build products, like dist/.

import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, "..", "..");

// Build order IS shelf order: build-preset appends each new id to the manifest,
// and the library renders the manifest's order. Sorting by era start date makes
// the scenario shelf read as a timeline — Bronze Age first, Millennium Dawn
// last — which for a history game beats alphabetical (which put "bronze" next
// to "coldwar") and beats popularity (which reshuffles the shelf as you play).
// Specs write their start date three ways and all three have to sort: ISO
// ("1939-09-01"), a leading minus for BC, and the spelled-out form the Bronze
// Age spec uses ("1200 BCE"). Reading only the leading "-" put the Bronze Age
// after Rome on the first run — the shelf order is only as good as this parser,
// so it is exported and pinned in tests/preset-shelf.mjs.
export const eraSortKey = (startDate) => {
  const text = String(startDate ?? "").trim();
  if (!text) return Number.POSITIVE_INFINITY; // undated specs sort last, visibly
  // NOT `\b` around the Korean alternative: JS word boundaries are ASCII-only
  // and never match beside Hangul — the same trap that let a Cyrillic border
  // relation pose as a polity in the OHM assembler.
  const bc = text.startsWith("-") || /\b(BCE?)\b/i.test(text) || text.includes("기원전");
  const digits = text.replace(/^-/, "").match(/\d+(?:-\d+)*/)?.[0] ?? "";
  const [yearText, monthText, dayText] = digits.split("-");
  const year = Number.parseInt(yearText, 10);
  if (!Number.isFinite(year)) return Number.POSITIVE_INFINITY;
  const month = Number.parseInt(monthText ?? "1", 10) || 1;
  const day = Number.parseInt(dayText ?? "1", 10) || 1;
  // Years count DOWN in BC and months still count UP inside one, which is what
  // adding the month/day to a negated year gives: 1200 BC Jan < 1200 BC Feb <
  // 1199 BC Jan.
  return bc ? -(year * 10000) + (month * 100 + day) : year * 10000 + month * 100 + day;
};

// Importing this file must not rebuild the world: tests pin eraSortKey, and a
// stray import that ran the fleet build would take minutes and rewrite every
// scenario folder as a side effect.
const isEntry = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));
if (isEntry) {
  const specFiles = readdirSync(__dirname).filter((name) => name.endsWith(".spec.mjs"));
  const dated = [];
  for (const name of specFiles) {
    const mod = await import(pathToFileURL(path.join(__dirname, name)).href);
    dated.push({ name, key: eraSortKey(mod.default?.game?.startDate), id: mod.default?.id ?? name });
  }
  dated.sort((a, b) => a.key - b.key || a.name.localeCompare(b.name));
  const specs = dated.map((entry) => entry.name);
  const undated = dated.filter((entry) => !Number.isFinite(entry.key)).map((entry) => entry.id);
  if (undated.length) console.log(`[rebuild-all] 시작일 없는 스펙(맨 뒤로): ${undated.join(", ")}`);
  console.log(`[rebuild-all] 연대순 진열: ${dated.map((entry) => entry.id).join(" → ")}`);
  if (specs.length === 0) {
    console.error("[rebuild-all] no *.spec.mjs found — nothing to build");
    process.exit(1);
  }

  console.log(`[rebuild-all] ${specs.length}개 프리셋 스펙 재생성:\n`);
  const failed = [];
  for (const spec of specs) {
    try {
      execFileSync(process.execPath, [path.join(__dirname, "build-preset.mjs"), path.join(__dirname, spec)], {
        cwd: PROJECT_ROOT,
        stdio: "inherit",
      });
    } catch {
      failed.push(spec);
    }
  }

  // THE BUILT-IN SCENARIO IS STAMPED FROM THE SAME SEED, AND IT DRIFTED.
  //
  // Every preset re-stamps regions-seed.geojson on each rebuild, so the fleet
  // follows the seed automatically — but "default" is generated by its own
  // script and nothing called it, so while the seed went 3,662 -> 4,920
  // features (Britain's counties, China's prefectures, India's districts) the
  // scenario a fresh game opens on stayed on the old map. The tool already
  // existed; only the wiring was missing. Now the seed cannot move without
  // default moving with it.
  //
  // It MERGES world.json (simulationRules, polityOverrides, storage all
  // survive) and only rewrites regions.geojson, colors.json, ownerCodes and
  // the ownership table.
  console.log("[rebuild-all] 기본 시나리오 지도 재생성:");
  try {
    execFileSync(process.execPath, [path.join(PROJECT_ROOT, "scripts", "build-default-map.mjs")], {
      cwd: PROJECT_ROOT,
      stdio: "inherit",
    });
  } catch {
    failed.push("build-default-map.mjs");
  }

  // AFTER the default map, never before: this pass compares each scenario
  // against the map the store will actually serve, and clearing a scenario
  // against a stale base is how a board starts borrowing the wrong owners.
  // It writes the overlay and backfills existing saves before removing a file.
  console.log("[rebuild-all] 공유 기본 지도 정리:");
  try {
    execFileSync(process.execPath, [path.join(__dirname, "share-base-map.mjs")], {
      cwd: PROJECT_ROOT,
      stdio: "inherit",
    });
  } catch {
    failed.push("share-base-map.mjs");
  }

  console.log("[rebuild-all] 프롬프트 팩 동기화:");
  try {
    execFileSync(process.execPath, [path.join(__dirname, "sync-prompts.mjs")], {
      cwd: PROJECT_ROOT,
      stdio: "inherit",
    });
  } catch {
    failed.push("sync-prompts.mjs");
  }

  // The manifest merge inside build-preset is idempotent — it appends ids it has
  // not seen and never reorders — so building in era order does not by itself
  // reorder an EXISTING shelf. Rewrite the order here, once, at the end: the
  // built-in default first, then the fleet in the order just built, then
  // everything else (community imports, the player's own scenarios) in the order
  // they already had. Only `order` is touched; the active/selected ids are the
  // player's and are copied through untouched.
  const manifestPath = path.join(PROJECT_ROOT, "server", "data", "scenario-manifest.json");
  if (existsSync(manifestPath)) {
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    const fleet = dated.map((entry) => entry.id).filter((id) => !failed.includes(`${id}.spec.mjs`));
    const previous = Array.isArray(manifest.order) ? manifest.order : [];
    const rest = previous.filter((id) => id !== "default" && !fleet.includes(id));
    const order = ["default", ...fleet, ...rest].filter((id, i, all) => all.indexOf(id) === i);
    if (JSON.stringify(order) !== JSON.stringify(previous)) {
      writeFileSync(manifestPath, `${JSON.stringify({ ...manifest, order }, null, 2)}\n`, "utf8");
      console.log(`[rebuild-all] 진열 순서 갱신: ${order.join(" → ")}`);
      if (rest.length) console.log(`[rebuild-all]   (프리셋 아닌 시나리오 ${rest.length}개는 기존 순서로 뒤에: ${rest.join(", ")})`);
    }
  }

  if (failed.length > 0) {
    console.error(`\n[rebuild-all] 실패 ${failed.length}건: ${failed.join(", ")} — 위 로그 확인`);
    process.exit(1);
  }
  console.log(`\n[rebuild-all] 완료 — ${specs.length}개 프리셋 + 프롬프트 동기화. 서버 재시작 후 시나리오 목록에서 확인.`);
  
}
